# Generated by Django 5.2 on 2025-06-12 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=200)),
                ('class_name', models.TextField(default='Break')),
                ('Subject_teacher', models.CharField(blank=True, max_length=250, null=True)),
                ('class_no', models.IntegerField()),
                ('class_room_no', models.CharField(max_length=100)),
                ('start_time', models.CharField(choices=[(datetime.datetime(1900, 1, 1, 8, 30), datetime.datetime(1900, 1, 1, 8, 30)), (datetime.datetime(1900, 1, 1, 9, 30), datetime.datetime(1900, 1, 1, 9, 30)), (datetime.datetime(1900, 1, 1, 10, 30), datetime.datetime(1900, 1, 1, 10, 30)), (datetime.datetime(1900, 1, 1, 11, 30), datetime.datetime(1900, 1, 1, 11, 30)), (datetime.datetime(1900, 1, 1, 12, 30), datetime.datetime(1900, 1, 1, 12, 30)), (datetime.datetime(1900, 1, 1, 13, 30), datetime.datetime(1900, 1, 1, 13, 30))], max_length=200)),
                ('end_time', models.CharField(choices=[(datetime.datetime(1900, 1, 1, 8, 30), datetime.datetime(1900, 1, 1, 8, 30)), (datetime.datetime(1900, 1, 1, 9, 30), datetime.datetime(1900, 1, 1, 9, 30)), (datetime.datetime(1900, 1, 1, 10, 30), datetime.datetime(1900, 1, 1, 10, 30)), (datetime.datetime(1900, 1, 1, 11, 30), datetime.datetime(1900, 1, 1, 11, 30)), (datetime.datetime(1900, 1, 1, 12, 30), datetime.datetime(1900, 1, 1, 12, 30)), (datetime.datetime(1900, 1, 1, 13, 30), datetime.datetime(1900, 1, 1, 13, 30)), ('15:30', '15:30')], max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
