# Generated by Django 5.2 on 2025-06-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedulair_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_table',
            old_name='Subject_teacher',
            new_name='subject_teacher',
        ),
        migrations.AlterField(
            model_name='time_table',
            name='end_time',
            field=models.CharField(choices=[('09:30', '09:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'), ('15:30', '15:30')], max_length=200),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='start_time',
            field=models.CharField(choices=[('08:30', '08:30'), ('09:30', '09:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30')], max_length=200),
        ),
    ]
