# Generated by Django 5.1.2 on 2025-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedulair_app', '0002_examschedule_holiday_alter_time_table_class_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_table',
            name='day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
