# Generated by Django 5.2 on 2025-06-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedulair_app', '0002_rename_subject_teacher_time_table_subject_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('time_table_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedulair_app.time_table')),
            ],
        ),
    ]
