# Generated by Django 5.2 on 2025-06-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedulair_app', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assignment', max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('issue_date', models.DateTimeField()),
                ('submission_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
